version: "2.2"
services:
  db:
    image: mysql
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: web
      MYSQL_USER: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snippetbox
    volumes:
      - /c/programdata/MySQL/data:/var/lib/mysql:rw
  web:
    build: .
    ports:
      - "4000:4000"
    container_name: golang_app
    depends_on:
      - db
volumes:
  mysql-data:      
        
